spring:

  datasource:
    url: jdbc:postgresql://terraform-20260501172556905200000004.ch2402mwo8yt.eu-west-3.rds.amazonaws.com:5432/budget_management
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true


server:
  servlet:
    session:
      cookie:
        secure: true
  address: 0.0.0.0
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info

python:
  service:
    url: http://python-service:5000